// src/components/Result.vue
<template>
    <tr>
        <td class="text-center text-muted info-col">{{result.tag}}</td>
        <!-- TODO: filter time format -->
        <!-- <td class="text-center text-muted info-col">{{result.dateTime | date:'HH:mm' : '+0100'}}</td> -->
        <td class="text-center text-muted info-col">{{result.dateTime}}</td>
        <td class="text-center text-muted info-col">{{result.pitch}}</td>
        <td class="text-right" :class="{'team-highlight': highlighted === result.homeTeam}" @click="highlight(result.homeTeam)">{{result.homeTeam}}</td>
        <td class="text-center points">{{homeScore}}</td>
        <td class="text-center points">{{awayScore}}</td>
        <td class="text-left" :class="{'team-highlight': highlighted === result.awayTeam}" @click="highlight(result.awayTeam)">{{result.awayTeam}}</td>
    </tr>
</template>

<script>
export default {
  name: 'result',
  props: ['pResult'],
  data: function() {
    return {
      result: this.pResult
    }
  },
  computed: {
    highlighted() {
      return this.$store.state.highlighted
    },
    homeScore() {
      let r = this.result
      if ('homeGoals' in r && r.homeGoals >= 0) {
        return r.homeGoals + (r.awayPens || r.homePens ? '(' + r.homePens + ')' : '');
      } else {
        return '';
      }
    },
    awayScore() {
      let r = this.result
      if ('awayGoals' in r && r.awayGoals >= 0) {
        return (r.awayPens || r.homePens ? '(' + r.awayPens + ')' : '') + r.awayGoals;
      } else {
        return '';
      }
    }
  },
  methods: {
    highlight: function(teamName) {
      if (this.highlighted !== teamName) {
        this.$store.commit('highlight', teamName);
      }
      else {
        this.$store.commit('highlight', '');
      }
    }
  }
}
</script>

// src/lib/Result.svelte
<script>
    import moment from 'moment-timezone';
    
    let time = function(dateTime) {
      return moment(dateTime).tz('Europe/London').format('hh:mm')
    }

    let homeScore = function(r) {
      if ('homeGoals' in r && r.homeGoals >= 0) {
        return r.homeGoals + (r.awayPens || r.homePens ? '(' + r.homePens + ')' : '');
      } else {
        return '';
      }
    }

    let awayScore = function(r) {
      if ('awayGoals' in r && r.awayGoals >= 0) {
        return (r.awayPens || r.homePens ? '(' + r.awayPens + ')' : '') + r.awayGoals;
      } else {
        return '';
      }
    }

    export let result = {}

</script>

<tr>
    <td class="text-center text-muted info-col">{result.tag}</td>
    <td class="text-center text-muted info-col">{time(result.dateTime)}</td>
    <td class="text-center text-muted info-col">{result.pitch}</td>
    <!--  :class="{'team-highlight': highlighted === result.homeTeam}" @click="highlight(result.homeTeam)" -->
    <td on:click={() => result.homeGoals += 1} class="text-right">{result.homeTeam}</td>
    <td class="text-center points">{homeScore(result)}</td>
    <td class="text-center points">{awayScore(result)}</td>
    <!--  :class="{'team-highlight': highlighted === result.homeTeam}" @click="highlight(result.homeTeam)" -->
    <td on:click={() => result.awayGoals += 1} class="text-left">{result.awayTeam}</td>
</tr>

<style>

</style>
